configurations:
  - sources:
      include:
        - FireModules/Sources/Shared/Networking/
    templates:
      - FireModules/Sources/Shared/Networking/CodeGen/Templates/
    output: FireModules/Sources/Shared/Networking/CodeGen/
    baseIndentation: 4
  - sources:
      include:
        - FireModules/Sources/Shared/SharedModels/
    templates:
      - FireModules/Sources/Features/SettingsFeature/CodeGen/Templates/
    output: FireModules/Sources/Features/SettingsFeature/CodeGen/
    baseIndentation: 4
    args:
      settingsView: DevSettingsView
      settingsStructure: DevSettings
      settingsExternalData: DevSettingsExternalData
      settingsImports:
        - SharedModels

  
