configurations:
  - sources:
      include:
        - FireModules/Sources/Networking/
    templates:
      - FireModules/Sources/Networking/CodeGen/Templates/
    output: FireModules/Sources/Networking/CodeGen/
    baseIndentation: 4
  # - sources:
  #     include:
  #       - FireModules/Sources/CoreUI/
  #     exclude:
  #       - FireModules/Sources/CoreUI/CodeGen/Templates/UIColorTemplate.stencil
  #   templates:
  #     - FireModules/Sources/CoreUI/CodeGen/Templates/
  #   output: FireModules/Sources/CoreUI/CodeGen/
  #   baseIndentation: 4
  
